Fixing broken PID/VID
lemmingDev/ESP32-BLE-Gamepad pull request #230
Opened 2024-10-03 03:11 UTC by Mystfit

Upstream NimBLE version 1.4.2 allows us to set the PID, VID and GUID normally without needing to flip high/low bytes. Using PNPVersionField to preserve backwards compatibility since it was added in the same upstream commit. If there's a better way to detect the upstream NimBLE version then that would probably be a better solution.

2024-10-03 03:53 UTC, Mystfit commented
Tested by running the CharacteristicsConfiguration example with VID set to 0xe502, PID set to 0xABCD and GUID set to 0x1234.

First I ran the sketch with the old behaviour and the following string was returned in Windows device manager for the Hardware IDs property: BTHLEDevice\{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&0102e5_PID&cdab_REV&3412
As you can see, the VID (ignoring first 01 byte), PID and REV properties have their first and second bytes flipped.

Then I re-ran the sketch with the fix applied that removes the VID, PID and GUID high/low bytes reversal and received the following: BTHLEDevice\{00001812-0000-1000-8000-00805f9b34fb}_Dev_VID&01e502_PID&abcd_REV&1234 which matches the provided PID, VID and GUID values.

I also tested this fix over in my EPS32-BLE-CompositeHID fork with my Xbox controller sketch. The VID and PID are vital for convincing Windows to load the correct Bluetooth LE XINPUT compatible input device driver and without the fix, Windows saw my board as a generic gamepad but with the fix, it started working again.

2024-11-23 13:40 UTC, lemmingDev commented
Thanks for submitting this fix

Sorry for the delay

Should it be

```
vid = configuration.getVid();
pid = configuration.getPid();
guidVersion = configuration.getGuidVersion();

#ifndef PNPVersionField
            high = highByte(guidVersion);
            and so on...
```

instead of

```
#ifndef PNPVersionField
          vid = configuration.getVid();
          pid = configuration.getPid();
          guidVersion = configuration.getGuidVersion();

          high = highByte(guidVersion);
          and so on...
```

so that vid, pid and guidVersion are taken from the user if set, instead of always using the defaults?

2024-11-23 19:55 UTC, lemmingDev requested changes
```#ifndef PNPVersionField```
needs to be moved under
```
vid = configuration.getVid();
pid = configuration.getPid();
guidVersion = configuration.getGuidVersion();
```

2024-11-23 19:59 UTC, lemmingDev commented
Might be quicker for me to just manually add the 2 lines,  though this would make you a contributor I guess ;)

2024-11-23 21:40 UTC, lemmingDev approved these changes
Nice

2024-11-23 21:46 UTC, lemmingDev approved these changes

2024-11-23 21:46 UTC, merged